version: '3'

services:
  reddit_django-redis:
    container_name: reddit_django-redis
    image: redis
    restart: always
  web:
    container_name: reddit_django
    build: .
    restart: always
    command: bash -c "python manage.py migrate && gunicorn reddit_django.wsgi --bind 0.0.0.0:8000 & celery -A reddit_django worker -l info"
    volumes:
      - .:/code
    depends_on:
      - reddit_django-redis
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.reddit_django.entrypoints=secure"
        - "traefik.http.routers.reddit_django.rule=Host(`reddit.$DOMAIN`)"
        - "traefik.http.services.reddit_django.loadbalancer.server.port=8000"
        - "traefik.http.routers.reddit_django.tls.certresolver=le"
    environment:
        - HEROKU_REDIS_ROSE_URL=redis://reddit_django-redis:6379

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
